### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by planetjoin** [lehuizi/hcloud-failover-keepalived#3]
Hello Alexander

Hetzner told me about your script.
I need something like this, but i not understand well if it can be useful for me.

I need to setup 2 VPS in Hetzner, hosting the same site in both VPS :
www.site.com
www.site.com
with files and mysql/mariaDB database

The idea is to set a load balancing script with failover, so if one of the vps is overloaded, or have a hardware issue, redirect to the other VPS and then the site is alwasy ON.

Regarding cluster / load balancing and intelligent failover, i think i also can use the cloudflare load balancing feature, but my problem is to get sync the files and database in this site.
I mean..

www.site.com under 1.1.1.1 vps (master site)
www.site.com under 2.2.2.2 vps (backup site)

when i add data in 1.1.1.1, that content must to be replicated on 2.2.2.2 , so if something happens in 1.1.1.1 it can redirect to 2.2.2.2 and display the same content.

Can i explain myself?
It can be done with your script ? you can help me ?
You can tell me the cost to help me in this?

Regards
Fabian

**Comment by lehuizi** [comment]
Hey,

this script can help you with a failover of your floating ips, not with the synchronization of your data.
Maybe you can sync the data for your websites with rsync and build a mariadb galera cluster for the database. You have to install a minimum of three servers for that setup.

With the hcloud-failover-keepalived script you can just switch floating ips from one destination to another. This is useful when you operate an haproxy or something like that.

Redards,
Alex

**Comment by planetjoin** [comment]
Thanks Alex for your answer!

Regards
Fabian
