### ISSUE TITLE
Readme - Keepalived Config

### ISSUE THREAD

**Issue by xha1** [lehuizi/hcloud-failover-keepalived#4]
Hello,

nice script and it is working fine. 

Is it possible to post a sample config for keepalived using your script?

**Comment by mraspor** [comment]
Well, I am also having troubles configuring keepalived config file to work correctly with the failover script. Any insight would be helpful.

**Comment by lehuizi** [comment]
I created a How-To
https://github.com/lehuizi/hcloud-failover-keepalived/blob/master/CONFIGURE_KEEPALIVED.md
